pub mod aggregation;
pub mod block_def;
pub mod block_grid;
pub mod block_id;
pub mod block_meta;
pub mod chunk_delta;
pub mod chunk_mesher;
pub mod chunk_storage;
pub mod client_chunks;
pub mod edit_pipeline;
pub mod meshing_adapter;
pub mod palette;
pub mod raycast;
pub mod registry;
pub mod serialization;
pub mod ship_grid;
pub mod sub_block;
pub mod sub_block_mesher;

pub use block_id::BlockId;
pub use block_def::{BlockDef, MaterialType, ToolType, LiquidProperties, HARDNESS_HP_MULTIPLIER, DAMAGE_STAGES};
pub use block_meta::{BlockMeta, BlockOrientation, BlockFlags};
pub use chunk_delta::{ChunkDelta, BlockEdit};
pub use chunk_storage::{ChunkStorage, DamageResult};
pub use palette::{PaletteStorage, CHUNK_SIZE, CHUNK_VOLUME, block_index, index_to_xyz};
pub use registry::{BlockRegistry, FunctionalBlockKind, InteractionSchema, InteractionDef, InteractionType, ThrusterProps};
pub use serialization::{serialize_chunk, deserialize_chunk, serialize_edit_wal, deserialize_edit_wal};
pub use ship_grid::{ShipGrid, build_starter_ship, StarterShipLayout};
